
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    include:
      - swagger
      - email
      - server
      - logging
      - database
      - redis
      - rabbitmq
      - druid
      - actuator
      - aliyun