# Spring Boot项目总的配置文件
spring:
  profiles:
    include:
      - main
      - mail
      - jpa
      - alibaba
      - swagger
      - auth
      - actuator
      - redis
      - sms
      - repository
      - jwt
      - opencv
      - druid
# 日志等级为DEBUG
logging:
  level:
    web: DEBUG

