# Spring Boot健康管理相关配置
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: beans, info, health, metrics
info:
  artifact-id: '@project.artifactId@'  # @xxx@是引用POM文件中的属性
  group-id: '@project.groupId@'
  name: '@project.name@'
  descript: '@project.description@'
  java-version: '@java.version@'
  author: Blessed Wang
  email: blessed@gmail.com

